name: CI/CD with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t cv-anshori:latest .

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no Dockerfile $VPS_USER@$VPS_HOST:/home/$VPS_USER/deploy/cv/
          ssh -i key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/$VPS_USER/deploy/cv
            docker build -t cv-anshori:latest .
            docker stop cv-anshori || true
            docker rm cv-anshori || true
            docker run -d --name cv-anshori -p 3001:3000 cv-anshori:latest
EOF
